# Generated by Django 4.2.4 on 2023-09-09 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionarios', models.IntegerField(default=0)),
                ('clientes', models.IntegerField(default=0)),
                ('fornecedores', models.IntegerField(default=0)),
                ('produtos', models.IntegerField(default=0)),
                ('empresas_terceiras', models.IntegerField(default=0)),
            ],
        ),
    ]
