# Generated by Django 4.2.4 on 2023-09-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado',
            name='nome_setor',
            field=models.CharField(default=30, max_length=30),
            preserve_default=False,
        ),
    ]
