# Generated by Django 4.2.4 on 2023-09-09 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0002_dado_nome_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dado',
            name='clientes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dado',
            name='empresas_terceiras',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dado',
            name='fornecedores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dado',
            name='funcionarios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dado',
            name='produtos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
